DROP TABLE PERSON;
DROP TABLE JOB;

CREATE TABLE JOB(
    JNO NUMBER(2) PRIMARY KEY,
    JNAME VARCHAR2(20) NOT NULL
);

CREATE TABLE PERSON(
    ID NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    JNO NUMBER(2) REFERENCES JOB(JNO),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3)
);

DROP SEQUENCE SEQ_PERSON;
CREATE SEQUENCE SEQ_PERSON
                START WITH 1 
                INCREMENT BY 1
                MAXVALUE 99999;
                
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, '모델');
INSERT INTO JOB VALUES (40, '감독');

SELECT * FROM JOB;

-- 1 입력
INSERT INTO PERSON VALUES (SEQ_PERSON.NEXTVAL, '정우성', 10,  99, 99, 99);
INSERT INTO PERSON VALUES (SEQ_PERSON.NEXTVAL, '김하늘', 10,  90, 99, 99);
INSERT INTO PERSON VALUES (SEQ_PERSON.NEXTVAL, '송혜교', 10,  90, 90, 99);

SELECT * FROM person;

COMMIT;
-- 2 직업별 출력 (총점포함해서 총점순으로 등수)
SELECT ROWNUM || '등' "RANK", S.*
FROM (SELECT NAME, J.JNAME, P.JNO, KOR, ENG, MAT, (KOR+ENG+MAT) "TOTAL" FROM PERSON P, JOB J WHERE P.JNO = J.JNO AND P.JNO= 10 ORDER BY TOTAL DESC) S;

SELECT P.*, JNAME, KOR+ENG+MAT SUM
FROM PERSON P, JOB J WHERE P.JNO = J.PNO AND P.JNO = 10 ORDER BY SUM DESC;

SELECT ROWNUM||'등' RANK, NAME||'('||ID||'번)' NAMEID, JNAME, KOR, ENG, MAT, SUM
FROM (SELECT P.*, JNAME, KOR+ENG+MAT SUM
      FROM PERSON P, JOB J WHERE P.JNO = J.JNO AND JNAME = '배우' ORDER BY SUM DESC);

-- 모두 출력. (총점을 포함해서 총점 순으로 등수)
SELECT ROWNUM || '등' "RANK", S.*
FROM (SELECT NAME, J.JNAME, P.JNO, KOR, ENG, MAT, (KOR+ENG+MAT) "TOTAL" FROM PERSON P, JOB J WHERE P.JNO = J.JNO ORDER BY TOTAL DESC) S;

SELECT ROWNUM||'등' RANK, NAME||'('||ID||'번)' NAMEID, JNAME, KOR, ENG, MAT, SUM
FROM (SELECT P.*, JNAME, KOR+ENG+MAT SUM
      FROM PERSON P, JOB J WHERE P.JNO = J.JNO ORDER BY SUM DESC);
      
SELECT JNAME FROM JOB;


-- 입력버튼 

INSERT INTO PERSON VALUES (SEQ_PERSON.NEXTVAL, '고소영', (SELECT JNO FROM JOB WHERE JNAME = '배우'), 90, 90, 90);

-- 검색 조회 

SELECT ROWNUM||'등' RANK, NAME||'('||ID||'번)' NAMEID, JNAME, KOR, ENG, MAT, SUM
FROM (SELECT P.*, JNAME, KOR+ENG+MAT SUM
      FROM PERSON P, JOB J WHERE P.JNO = J.JNO AND JNAME = '배우' ORDER BY SUM DESC);
      
-- 모두 조회
