DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    ID VARCHAR2(20) PRIMARY KEY,
    PW VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    PHONE1 VARCHAR2(10),
    PHONE2 VARCHAR2(10),
    PHONE3 VARCHAR2(10),
    GENDER VARCHAR2(10)
);

COMMIT;

SELECT * FROM MEMBER;
SELECT ID, PW, NAME, PHONE1||'-'||PHONE2||'-'||PHONE3 PHONE, GENDER FROM MEMBER;
-- JOIN 시 필요한 쿼리.
INSERT INTO MEMBER VALUES('AAA', '111', '이데이', '010', '9999', '9999', '남자');
INSERT INTO MEMBER VALUES('sonson', 'stonker', '이손손', null, null, null, '여자');

-- 로그인 시 필요한 쿼리.
SELECT * FROM MEMBER WHERE ID = 'AAA' AND PW = '111';

-- 회원 정보 수정시 필요한 쿼리.
SELECT * FROM MEMBER WHERE ID = 'AAA';

UPDATE MEMBER SET NAME = '이승훈', PW = 'leos26', PHONE1 = '02', PHONE2 = '8888', PHONE3= '8888', GENDER = '여자' WHERE ID = 'aaa';

DELETE FROM MEMBER WHERE ID = 'leodays';