DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    ID VARCHAR2(20) PRIMARY KEY,
    PW VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(20)
);

INSERT INTO MEMBER VALUES('aaa', '111', '이데이', '010-9999-9999');
INSERT INTO MEMBER VALUES('bbb', '222', '손오공',NULL);

COMMIT;

-- 2. semimember/memberView.jsp
SELECT ID, PW, NAME, NVL(PHONE,'연락처 없음') PHONE FROM MEMBER;