-- MYSQL
SHOW DATABASES;
USE LEOSDATABASE;
SELECT * FROM DIVISION WHERE DNO = 10;
SELECT PNO, PNAME, MANAGER, STARTDATE FROM PERSONAL WHERE DNO = 10;

select * from division;
INSERT INTO division VALUES (50, 'IT', 'jongro'); 
-------------------------------------------------------------------

SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM DEPT WHERE deptno = 10;

SELECT * FROM EMP WHERE DEPTNO = 10;
SELECT * FROM DEPT WHERE DNAME = 'SALES';

SELECT * 
FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO AND DNAME = 'SALES';

SELECT empno, ename, job, mgr, hiredate, sal, e.deptno, dname, loc  
FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO
AND DNAME = UPPER('research');

INSERT INTO DEPT VALUES (50, 'IT', 'JONGRO');
INSERT INTO DEPT VALUES (60, 'etc', 'kangnam');

UPDATE DEPT SET DNAME = 'IT' WHERE DEPTNO = 50; 

UPDATE DEPT SET DNAME = 'OP', LOC ='JONGRO' WHERE DEPTNO = 90;

DELETE FROM DEPT WHERE DEPTNO = 50;

--- PREPAREDSTATEMEMT 객체의 2번째 용도 예제 TABLE
DROP TABLE PHOTOINFO;
CREATE TABLE PHOTOINFO(
    ID VARCHAR2(20) PRIMARY KEY, -- ID 문자 20자이내
    PHOTO BLOB                   -- PHOTO 파일
);

SELECT * FROM PHOTOINFO;
SELECT * FROM PHOTOINFO WHERE ID = 'testID';

COMMIT;