DROP TABLE MVC_BOARD;

CREATE TABLE MVC_BOARD(
    BID NUMBER(6) PRIMARY KEY,
    BNAME VARCHAR2(30) NOT NULL,
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT VARCHAR2(1000) NOT NULL,
    BDATE DATE DEFAULT SYSDATE,
    BHIT NUMBER(6) DEFAULT 0,
    BGROUP NUMBER(6) NOT NULL,
    BSTEP NUMBER(3) NOT NULL,
    BINDENT NUMBER(3) NOT NULL,
    BIP VARCHAR2(20) NOT NULL
);

DROP SEQUENCE MVC_BOARD_SEQ;
CREATE SEQUENCE MVC_BOARD_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999
    MINVALUE 1
    NOCYCLE
    NOCACHE;

-- LIST.JSP TOP-N  구문 (게시판 페이징 기능)
SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP ASC;

SELECT ROWNUM RN, A.* FROM (SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP ASC) A);

SELECT * FROM 
(SELECT ROWNUM RN, A.* FROM (SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP ASC) A)
WHERE RN BETWEEN 1 AND 150;

--글의 갯수를 구함
SELECT COUNT(*) FROM MVC_BOARD;

-- 특정글을 가져옴.
SELECT * FROM MVC_BOARD WHERE BID = 11;

-- 글쓰기
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP) 
VALUES ( MVC_BOARD_SEQ.NEXTVAL, '이데이', '제목', '본문', MVC_BOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');

-- 조회수 1 증가
UPDATE MVC_BOARD SET BHIT = BHIT + 1 WHERE BID = 11; 

--답변 글일 경우 글쓰기 전 해야하는 것 (A STEP)
UPDATE MVC_BOARD SET  BSTEP = BSTEP + 1 
WHERE BGROUP = 2 AND BSTEP > 0; 

-- 글 수정
UPDATE MVC_BOARD SET BNAME = '이유리', 
                     BTITLE = '제목', 
                     BCONTENT = '새 본문'
                WHERE BID = 11; 

-- 글 삭제
DELETE FROM MVC_BOARD WHERE BID = 1;
COMMIT;