DROP TABLE CUSTOMER;
DROP TABLE CGRADE; 

CREATE TABLE CGRADE (
	GNO NUMBER(2) PRIMARY KEY,
	GRADE VARCHAR2(10) NOT NULL
);

CREATE TABLE CUSTOMER (
    CNO VARCHAR2(4) PRIMARY KEY,
    CTEL VARCHAR2(20) NOT NULL, 
    CNAME VARCHAR2(30) NOT NULL,
    POINT NUMBER(10) DEFAULT 1000, 
    BUY NUMBER(30) DEFAULT 0,
    GNO NUMBER(2) REFERENCES CGRADE(GNO)
);


-- 고객 번호 시퀀스
DROP SEQUENCE SEQ_CNO;
CREATE SEQUENCE SEQ_CNO MAXVALUE 9999;

-- TABLE 생성 확인
SELECT * FROM CGRADE;
SELECT * FROM CUSTOMER;

-- 고객 등급 데이터 입력
INSERT INTO CGRADE VALUES (1, '일반');
INSERT INTO CGRADE VALUES (2, '실버');
INSERT INTO CGRADE VALUES (3, '골드');
INSERT INTO CGRADE VALUES (4, 'VIP');
INSERT INTO CGRADE VALUES (5, 'VVIP');


-- 고객 데이터 입력
INSERT INTO CUSTOMER VALUES (SEQ_CNO.NEXTVAL, '010-9999-9999', '이데이', 1000, 0, 1);
INSERT INTO CUSTOMER VALUES (SEQ_CNO.NEXTVAL, '010-9999-8888', '이만화', 1000, 0, 1);
INSERT INTO CUSTOMER VALUES (SEQ_CNO.NEXTVAL, '010-9999-7777', '이유리', 1000, 0, 1);
INSERT INTO CUSTOMER VALUES (SEQ_CNO.NEXTVAL, '010-9999-6666', '강바다', 1000, 0, 1);
INSERT INTO CUSTOMER VALUES (SEQ_CNO.NEXTVAL, '010-9999-5555', '우마왕', 1000, 0, 1);

COMMIT;

-- 콤보 박스
SELECT GRADE FROM CGRADE;

-- 1. 폰 검색
SELECT C.*, G.GRADE
FROM CUSTOMER C, CGRADE G
WHERE C.GNO = G.GNO AND SUBSTR(CTEL, -4) = '8888';

-- 2.고객이름 검색
SELECT C.*, G.GRADE
FROM CUSTOMER C, CGRADE G
WHERE C.GNO = G.GNO AND CNAME = '이유리';

-- 3.포인트 구매
UPDATE CUSTOMER SET BUY = (BUY + 1000) , POINT = (POINT - 1000) WHERE SUBSTR(CTEL, -4) = '8888';  

-- 4.물품구매
UPDATE CUSTOMER SET BUY = (BUY + 1000) WHERE SUBSTR(CTEL, -4) = '8888';  


-- 5.등급별 출력 
SELECT C.*, G.GRADE
FROM CUSTOMER C, CGRADE G
WHERE C.GNO = G.GNO
ORDER BY CNO;

SELECT C.*, G.GRADE
FROM CUSTOMER C, CGRADE G
WHERE C.GNO = G.GNO
GROUP BY C.GNO;

-- 6.전체 출력
SELECT C.*, G.GRADE
FROM CUSTOMER C, CGRADE G
WHERE C.GNO = G.GNO
ORDER BY C.CNO;

-- 7.회원가입
INSERT INTO CUSTOMER VALUES (SEQ_CNO.NEXTVAL, '010-9999-7890', '이요이', 1000, 0, 1);

-- 8.회원 연락처 수정
UPDATE CUSTOMER SET CTEL = '010-8888-9999' WHERE CNAME = '이유리';

-- 9.회원 탈퇴
DELETE FROM CUSTOMER WHERE CNAME = '우마왕';

COMMIT;