drop table MVC_MEMBER;
drop table MVC_BOARD;

drop table BOOK2;

drop table ADMIN;

CREATE TABLE MVC_MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MEMAIL VARCHAR2(30),
    MPHOTO VARCHAR2(30) DEFAULT 'nothing.jpg',
    MBIRTH DATE,
    MADDRESS VARCHAR2(300) NOT NULL,
    MRDATE DATE NOT NULL
);

DROP SEQUENCE MVC_BOARD_SEQ;
CREATE SEQUENCE MVC_BOARD_SEQ;

CREATE TABLE MVC_BOARD(
    BID NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES MVC_MEMBER (MID),
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT VARCHAR2(1000) NOT NULL,
    BDATE DATE NOT NULL,
    BHIT NUMBER(6) NOT NULL,
    BGROUP NUMBER(6) NOT NULL,
    BSTEP NUMBER(3) NOT NULL,
    BINDENT NUMBER(3) NOT NULL,
    BIP VARCHAR2(20) NOT NULL
);

CREATE TABLE ADMIN(
    AID VARCHAR2(30) PRIMARY KEY,
    APW VARCHAR2(30) NOT NULL,
    ANAME VARCHAR2(30) NOT NULL
);

DROP SEQUENCE BOOK2_SEQ;
CREATE SEQUENCE BOOK2_SEQ;

CREATE TABLE BOOK2(
    BID NUMBER(5) PRIMARY KEY,
    BTITLE VARCHAR2(100) NOT NULL,
    BPRICE NUMBER(7) NOT NULL,
    BIMAGE1 VARCHAR2(100) NOT NULL,
    BIMAGE2 VARCHAR2(100) NOT NULL,
    BCONTENT VARCHAR2(1000),
    BDISCOUNT NUMBER(3) NOT NULL
);

SELECT * FROM MVC_MEMBER;
SELECT * FROM MVC_BOARD;
SELECT * FROM ADMIN;
SELECT * FROM BOOK2;
------------------ MVC_MEMBER
--멤버 리스트 보기
SELECT * FROM
    (SELECT ROWNUM RN, A.* FROM (SELECT * FROM MVC_MEMBER ORDER BY MRDATE) A)
        WHERE RN BETWEEN 1 AND 10;

-- 글의 행수 구하기
SELECT COUNT(*) FROM MVC_MEMBER;

-- 가입 멤버 비교 : 가입멤버 보기()
SELECT * FROM MVC_MEMBER WHERE MID = 'leos';

-- 가입 처리 
INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS, MRDATE) 
    VALUES ('leo','111','이데이','leo@gmail.com','photo1.jpg','1982-09-16','서울시 도봉구', SYSDATE);
    
INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS, MRDATE) 
    VALUES ('DAYS','111','이데이','leo@gmail.com','photo1.jpg','1982-09-16','서울시 도봉구', SYSDATE);

COMMIT;

-- 가입멤버 수정
UPDATE MVC_MEMBER SET 
            MPW = '222', 
            MNAME = '이유리', 
            MEMAIL = 'yu@gmail.com', 
            MPHOTO = 'photo2.jpg', 
            MBIRTH = '1990-09-12', 
            MADDRESS = '서울시 종로구'
WHERE MID = 'leos';

--가입 멤버 탈퇴 
DELETE FROM MVC_MEMBER WHERE MID = 'leo'AND MPW = '111';

------------------ MVC_board
--글 리스트 보기
SELECT * FROM
(SELECT ROWNUM RN, A.* FROM
(SELECT B.*, M.MNAME, M.MEMAIL FROM MVC_BOARD B, MVC_MEMBER M 
    WHERE B.MID = M.MID ORDER BY BGROUP DESC, BSTEP ASC) A)
WHERE RN BETWEEN 1 AND 10;

-- 글의 행수 구하기
SELECT COUNT(*) FROM MVC_BOARD;

-- 상세 글보기 : 
SELECT * FROM MVC_BOARD WHERE BID = 4;

-- 글쓰기 처리 
INSERT INTO MVC_BOARD (BID, MID, BTITLE, BCONTENT, BDATE, BHIT, BGROUP, BSTEP, BINDENT, BIP) 
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'leo','글제목','글내용', SYSDATE, 0, MVC_BOARD_SEQ.CURRVAL , 0, 0, '127.0.0.1');

COMMIT;

-- 글수정
UPDATE MVC_BOARD SET 
            BTITLE = '수정제목',
            BCONTENT '수정글',
            BDATE = SYSDATE,
            BIP = '127.0.0.1'
WHERE MID = 'leos';

--글삭제  
DELETE FROM MVC_BOARD WHERE BID = 1;

---------------------- ADMIN
--관리자 리스트 보기
SELECT * FROM ADMIN;

-- 관리자 행수 구하기
SELECT COUNT(*) FROM ADMIN;

-- 관리자 상세보기 :  중복 체크 로그인 
SELECT * FROM ADMIN WHERE AID = 'DAYS';

-- 관리자 가입 처리 
INSERT INTO ADMIN (AID, APW, ANAME) 
    VALUES ('DAYS', '1234', '이데이');

COMMIT;

-- 관리자 수정
UPDATE ADMIN SET 
            APW  = '5678',
            ANAME = '이루리'
WHERE AID = 'DAYS';

-- 관리자 삭제   
DELETE FROM ADMIN WHERE AID = 'DAYS';

------------------ BOOK2
--책 리스트 보기
SELECT * FROM
    (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK2 ORDER BY BID) A)
        WHERE RN BETWEEN 1 AND 10;

-- 책 테이블 행수 구하기
SELECT COUNT(*) FROM BOOK2;

-- 책 상세 보기 : 
SELECT * FROM BOOK2 WHERE BID = 1;

-- 책 입력
INSERT INTO BOOK2 (BID, BTITLE, BPRICE, BIMAGE1, BIMAGE2, BCONTNENT, BDISCOUNT) 
    VALUES (BOOK2_SEQ.NEXTVAL, 'JAVA', 20000, 'photo1.jpg', 'photo2.jpg', '자바책 소개', 10);

COMMIT;

-- 가입멤버 수정
UPDATE BOOK2 SET 
            BTITLE = 'PHP',
            BPRICE = 30000,
            BIMAGE1 = 'BOOK1.JPG',
            BIMAGE2 = 'BOOK1.JPG',
            BCONTENT = 'PHP 소개',
            BDISCOUNT = 15
WHERE BID = 1;

--가입 멤버 탈퇴 
DELETE FROM BOOK2 WHERE BID = 1;



