
DROP TABLE FILEBOARD;
DROP TABLE CUSTOMER;
DROP TABLE BOOK;

DROP SEQUENCE FILEBOARD_SEQ;
DROP SEQUENCE BOOK_SEQ;

CREATE TABLE CUSTOMER (
    CID VARCHAR2(20) PRIMARY KEY,
    CPW VARCHAR2(20) NOT NULL,
    CNAME VARCHAR2(30) NOT NULL,
    CTEL VARCHAR2(20),
    CEMAIL VARCHAR2(30) NOT NULL,
    CGENDER VARCHAR2(20),
    CADDR VARCHAR2(100)
);

CREATE SEQUENCE FILEBOARD_SEQ;

CREATE TABLE FILEBOARD (
    FNUM NUMBER(9) PRIMARY KEY,
    CID VARCHAR2(20) REFERENCES CUSTOMER(CID),
    FSUBJECT VARCHAR2(300) NOT NULL,
    FCONTENT VARCHAR2(300) NOT NULL,
    FFILENAME VARCHAR2(100),
    FREADCOUNT NUMBER(5) NOT NULL,
    FPW VARCHAR2(30) NOT NULL,
    FREF NUMBER(5) NOT NULL,
    FRESTEP NUMBER(5) NOT NULL,
    FRELEVEL NUMBER(5) NOT NULL,
    FIP VARCHAR2(20) NOT NULL,
    FRDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE BOOK_SEQ;

CREATE TABLE BOOK (
    BID NUMBER(5) PRIMARY KEY,
    BTITLE VARCHAR2(100) NOT NULL,
    BPRICE NUMBER(10) NOT NULL,
    BIMAGE1 VARCHAR2(50) DEFAULT 'nothing.jpg',
    BIMAGE2 VARCHAR2(50) DEFAULT 'nothing.jpg',
    BCONTENT VARCHAR2(1000),
    BDISCOUNT NUMBER(3)
);

--  테이블 생성 확인
SELECT * FROM CUSTOMER;
SELECT * FROM FILEBOARD;
SELECT * FROM BOOK;
---------------------------------------- CUSTOMER
-- CustomerDao의 confirmId와 회원가입
SELECT * FROM CUSTOMER WHERE CID='aaa';

INSERT INTO CUSTOMER VALUES
    ('aaa','111','홍','9999-9999','h@h','m','서울종로');
    
commit;

-- CustomerDao의 로그인
SELECT * FROM CUSTOMER WHERE CID='aaa';

-- CustomerDao의 회원정보 수정
UPDATE CUSTOMER SET CPW='111', CNAME='박',
    CTEL='8888-8888', CEMAIL='A@A', CGENDER='f',
    CADDR='서울시' WHERE CID='aaa';
    
-- 메인화면에서 쓸 회원정보 리스트(페이징 안되는거)
SELECT * FROM CUSTOMER ORDER BY CID;

-- 메인화면에서 쓸 회원정보 리스트(페이징 되는 거 만들어보자)
SELECT ROWNUM RN, A.* FROM
    (SELECT * FROM CUSTOMER ORDER BY CID) A;
    
SELECT * FROM 
    (SELECT ROWNUM RN, A.* FROM
        (SELECT * FROM CUSTOMER ORDER BY CID) A)
    WHERE RN BETWEEN 2 AND 3;
-- 테이블의 데이터 행수 구하기
SELECT COUNT(*) FROM CUSTOMER;

----------------------------------------- FileBoard

-- FILEBoardDao의 글갯수 리턴
SELECT COUNT(*) FROM FILEBOARD;

-- FILEBoardDao의 글 입력
INSERT INTO FILEBOARD VALUES (FILEBOARD_SEQ.NEXTVAL, 'aaa','제목','본문\n입니다', NULL, 0, '11', 
                              FILEBOARD_SEQ.CURRVAL, 0,0,'127.0.0.1',SYSDATE);

-- FILEBoardDao의 글목록
SELECT F.*, C.CNAME, C.CEMAIL FROM FILEBOARD F, CUSTOMER C
    WHERE F.CID=C.CID ORDER BY FNUM DESC;

SELECT ROWNUM RN, A.* FROM 
    (SELECT F.*, C.CNAME, C.CEMAIL FROM FILEBOARD F, CUSTOMER C
    WHERE F.CID=C.CID ORDER BY FNUM DESC) A;

SELECT *
    FROM (SELECT ROWNUM RN, A.* FROM 
    (SELECT F.*, C.CNAME, C.CEMAIL FROM FILEBOARD F, CUSTOMER C
    WHERE F.CID=C.CID ORDER BY FREF DESC, FRESTEP ASC) A)
    WHERE RN BETWEEN 1 AND 100; -- 페이징처리에서 쓸 TOP-N구문

-- 답변글 추가 전 해야할 ⓐ STEP   
UPDATE FILEBOARD SET FRESTEP = FRESTEP + 1 WHERE FREF = 1 AND FRESTEP > 0;

-- FILEBoardDao의 글 상세보기
UPDATE FILEBOARD SET FREADCOUNT = FREADCOUNT + 1 WHERE FNUM=1;
SELECT F.*, C.CNAME, C.CEMAIL FROM FILEBOARD F, CUSTOMER C
    WHERE F.CID=C.CID AND F.FNUM=1;

commit;

-- 글 수정
UPDATE FILEBOARD SET 
    FSUBJECT = '제',
    FFILENAME = NULL,
    FCONTENT = '본',
    FREADCOUNT = 11,
    FPW = '11',
    FIP = '127.0.0.1'
    WHERE FNUM = 1;
-- 글삭제
DELETE FROM FILEBOARD WHERE FNUM=1 AND FPW='11';
DELETE FROM FILEBOARD;
ROLLBACK;
--------------------------------------------- Book

-- 책 등록
INSERT INTO BOOK VALUES (BOOK_SEQ.NEXTVAL, 'JSP',20000,'nothing.jpg','nothing.jpg',
        'jsp 2.3 웹프로그래밍기초부터 중급까지',0); -- DAO 사용
        
INSERT INTO BOOK (BID, BTITLE, BPRICE, BCONTENT ,BDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, 'sPRING',10000, '스프링4.0책',10);
    
INSERT INTO BOOK (BID, BTITLE, BPRICE, BCONTENT, BIMAGE1, BDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, 'sPRING',10000,'NOTHING.JPG', '스프링4.0책',10);
    
INSERT INTO BOOK (BID, BTITLE, BPRICE, BCONTENT, BIMAGE2, BDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, 'sPRING',10000,'NOTHING.JPG','스프링4.0책', 10);

-- 책 목록 보기
SELECT * FROM BOOK ORDER BY BID DESC;
SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY BID DESC) A;

SELECT * FROM (SELECT ROWNUM RN, A.* FROM 
            (SELECT * FROM BOOK ORDER BY bID DESC) A)
    WHERE RN BETWEEN 3 AND 4;  -- 페이징처리에 쓸 TOP-N구문
    
-- 특정책의 상세보기
SELECT * FROM BOOK WHERE BID=1;

-- 등록된 책 갯수
SELECT COUNT(*) FROM BOOK;

